// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: nvidia.proto

package nvidia

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NVIDIA_Generate_FullMethodName = "/nvidia.NVIDIA/Generate"
)

// NVIDIAClient is the client API for NVIDIA service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NVIDIAClient interface {
	// gRPC service information
	Generate(ctx context.Context, in *NVIDIARequest, opts ...grpc.CallOption) (*NVIDIAResponse, error)
}

type nVIDIAClient struct {
	cc grpc.ClientConnInterface
}

func NewNVIDIAClient(cc grpc.ClientConnInterface) NVIDIAClient {
	return &nVIDIAClient{cc}
}

func (c *nVIDIAClient) Generate(ctx context.Context, in *NVIDIARequest, opts ...grpc.CallOption) (*NVIDIAResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NVIDIAResponse)
	err := c.cc.Invoke(ctx, NVIDIA_Generate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NVIDIAServer is the server API for NVIDIA service.
// All implementations must embed UnimplementedNVIDIAServer
// for forward compatibility.
type NVIDIAServer interface {
	// gRPC service information
	Generate(context.Context, *NVIDIARequest) (*NVIDIAResponse, error)
	mustEmbedUnimplementedNVIDIAServer()
}

// UnimplementedNVIDIAServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNVIDIAServer struct{}

func (UnimplementedNVIDIAServer) Generate(context.Context, *NVIDIARequest) (*NVIDIAResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Generate not implemented")
}
func (UnimplementedNVIDIAServer) mustEmbedUnimplementedNVIDIAServer() {}
func (UnimplementedNVIDIAServer) testEmbeddedByValue()                {}

// UnsafeNVIDIAServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NVIDIAServer will
// result in compilation errors.
type UnsafeNVIDIAServer interface {
	mustEmbedUnimplementedNVIDIAServer()
}

func RegisterNVIDIAServer(s grpc.ServiceRegistrar, srv NVIDIAServer) {
	// If the following call pancis, it indicates UnimplementedNVIDIAServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NVIDIA_ServiceDesc, srv)
}

func _NVIDIA_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NVIDIARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NVIDIAServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NVIDIA_Generate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NVIDIAServer).Generate(ctx, req.(*NVIDIARequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NVIDIA_ServiceDesc is the grpc.ServiceDesc for NVIDIA service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NVIDIA_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nvidia.NVIDIA",
	HandlerType: (*NVIDIAServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Generate",
			Handler:    _NVIDIA_Generate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nvidia.proto",
}
